version: '3.8'
services:
  nextcloud:
    container_name: nextcloud
    privileged: true
    image: docker.sunet.se/drive/nextcloud-custom:26.0.3.3-4
    ports:
      - 8000:80
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/local_apps:/local_apps
      - ./nextcloud/scripts:/scripts
      - /dev/fuse:/dev/fuse
    environment:
      INSTANCEID: octoue9ym05u
      JWT_KEY: RoafObyacMagwemNihinabewegdyotjienPicKac
      MYSQL_PASSWORD: nextcloud
      PASSWORDSALT: hzmRixRvv/EfSSPNaW4rzJb3HuNqaW
      S3_KEY: EJ39ITYZEUH5BGWDRUFY
      S3_SECRET: M5MrXTRjkyMaxXPe2FRXMTfTfbKEnZCu+7uRTVSj
      SECRET: rvYyvVajC9W07ncVDwEWGYp/bLczQkMl/kmzLlrEl5d288sg
    entrypoint:
      - /scripts/entrypoint.sh
    command:
      - apache2-foreground
  gss:
    container_name: gss
    privileged: true
    image: docker.sunet.se/drive/nextcloud-custom:26.0.3.3-4
    ports:
      - 8001:80
    volumes:
      - ./gss/config:/config
    environment:
      INSTANCEID: ocv97i5mvjzf
      JWT_KEY: RoafObyacMagwemNihinabewegdyotjienPicKac
      MYSQL_PASSWORD: gss
      PASSWORDSALT: TxBvoYLatUxpP76k/eI3RIxmQqffUy
      SECRET: NqYBemdyPKfmWRpBeH9jRsKNI3pGJpBc9SaJs8j1YvXycAJw
  garage:
    container_name: garage
    image: dxflrs/garage:v0.8.0
    ports:
      - 3900:3900
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/data:/var/lib/garage/data
      - ./garage/bin/busybox:/bin/busybox
      - ./garage/meta:/var/lib/garage/meta
      - ./garage/scripts/entrypoint.sh:/entrypoint.sh
    environment:
      S3_KEY: EJ39ITYZEUH5BGWDRUFY
      S3_SECRET: M5MrXTRjkyMaxXPe2FRXMTfTfbKEnZCu+7uRTVSj
    command:
      - /bin/busybox
      - sh
      - /entrypoint.sh
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - ./mariadb/init.d:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - mariadb
